### ISSUE TITLE
Remove zkEVM OZ Injector Poker upon activation of new Poker

### ISSUE THREAD

**Issue by Xeonus** [BalancerMaxis/OZ-Automation#18]
Once https://github.com/BalancerMaxis/multisig-ops/pull/1507 is executed make sure to

Disable[OZ defender job](https://defender.openzeppelin.com/#/actions/automatic/3c54289e-5e3c-4ef5-9016-25a9bb511500?tab=generalInfo)
by setting the disable flag on [ OZ Defender dependencies in the deployment repository](https://github.com/BalancerMaxis/OZ-Automation/tree/main/tasks/Polygon%20ZkEVM%20Upkeeper)

so that for any future deployments it stays disabled. We should not delete the code for now.

**Comment by gosuto-inzasheru** [comment]
1. i moved the ticket from msig ops to this repo
2. pr#1507 is execd

**Comment by gosuto-inzasheru** [comment]
@Xeonus i paused it through the oz ui, is that enough or not?

**Comment by Xeonus** [comment]
@gosuto-inzasheru we need to modify the js file to disable the job, so if we do another deployment with additional changes, it will not be overwritten and enabled again. Adjusted specs to make that clear

**Comment by Xeonus** [comment]
Resolved with https://github.com/BalancerMaxis/OZ-Automation/pull/20
