### ISSUE TITLE
investigate vebalfeeinjector action

### ISSUE THREAD

**Issue by gosuto-inzasheru** [BalancerMaxis/OZ-Automation#19]
i see it as active in the oz ui, but i believe it has been replaced by https://automation.chain.link/mainnet/37139378590340576488101784362222889752237871948060516894495194681064041951097

the injector appears to have `0x4249093e75b2eECA9f3ba3171eA1f3fA186ABE9D` as its keeper, which is indeed the chainlink forwarder we see in their ui

**Comment by Hyferion** [comment]
Indeed, the keeper's address is from Chainlink.

I will disable the vebalfeeinjector on OZ as "0x8AD2512819A7eae1dd398973EFfaE48dafBe8255" is the only contract it upkeeps.
